### ISSUE TITLE
Use riemann's scheduling instead of at-at

### ISSUE THREAD

**Issue by samplerr** [samplerr/samplerr#3]
Currently we use `overtone/at-at` to schedule alias rotation.
This has two drawbacks:
1. pulls in another dependency
2. we don't properly reload on `SIGHUP`

riemann provides scheduling capabilities through `service!` see _e.g._ `periodically-expire`.
We should definitely use that instead.

**Comment by faxm0dem** [comment]
Fixed by 83622d4
